# Site settings
title: Escape the Everyday
locale: uk
partner:
  name: Visit Britain
  link: "#client-name"

description: >
  Win one of six irresistable staycations! For the chance of winning an escape from the day-to-day, be it the wild outdoors or the city lights, select your perfect getaway below.



# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/visitbritain" # the subpath of your site, e.g. /blog/
img:     "/uk/2020/visitbritain/_assets/img"
css:     "/uk/2020/visitbritain/_assets/css"
js:      "/uk/2020/visitbritain/_assets/js"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed