# Site settings
title: Escape the Everyday
locale: uk
partner:
  name: Visit Britain
  link: "https://ad.doubleclick.net/ddm/trackclk/N6198.1692340.SECRETESCAPES.COM/B24629302.282126383;dc_trk_aid=476094911;dc_trk_cid=137683884;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;gdpr=${GDPR};gdpr_consent=${GDPR_CONSENT_755}"

description: >
  Win one of six irresistable staycations! For the chance of winning an escape from the day-to-day, be it the wild outdoors or the city lights, select your perfect getaway below.



# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/visitbritain" # the subpath of your site, e.g. /blog/
img:     "/uk/2020/visitbritain/_assets/img"
css:     "/uk/2020/visitbritain/_assets/css"
js:      "/uk/2020/visitbritain/_assets/js"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed